### PR TITLE
feat: add case sensitivity for command search and improve suggestion rendering

### PR DESCRIPTION
**Pull request by M1n-74316D65**
I made this for me, so why not do a PR :)

- Added a case sensitivity config for commands
- Improved the suggestion when adding a /

### CODE REVIEW

**Comment by M1n-74316D65** [comment]
Doesn't work when using Uppercase

**Comment by xvvvyz** [comment]
Hi @M1n-74316D65, thanks for the PR! I am not sure I understand the purpose of case insensitive commands. If it's just a stylistic thing so the grid has uppercase keys you could text-transform on .key with CSS. As for the improved suggestions, how are they improved? A screenshot or description would be helpful (:

**Comment by M1n-74316D65** [comment]
Ohh yeah, it’s pretty lacking in explanation 😅. [start.m1n.land](https://start.m1n.land/)

- The case sensitivity was added so that if you write a command in uppercase and it's stored in lowercase (or vice versa), it'll still work, making the command matching more flexible regardless of case.

  Screenshot 2024-09-30 at 23-24-22 M1n Startpage
  
  Screenshot 2024-09-30 at 23-24-36 M1n Startpage


- As for the improved suggestions, previously when writing a subcommand and adding a /, the suggestions disappeared. Now they stay visible, making it easier to continue selecting commands.


  Screenshot 2024-09-30 at 23-24-50 M1n Startpage


I put this together pretty quickly, half with AI 😄, so if you need any changes or prefer to handle it yourself, feel free! I’m not super familiar with vanilla JS. If this doesn’t align with the direction you're going, no hard feelings at all if you decide to close the PR.

**Comment by xvvvyz** [comment]
Ah, understood. Yeah, I don't have a need for case insensitivity and if I am going to use a command suggestion I just tab to it and don't continue typing. I appreciate the PR and explanation, though.

**Pull request closed without merging**
